#!/usr/bin/env nu

let root = ($env.FILE_PWD | path join ".." ".." | path expand)
cd $root

def run-cmd [cmd: string] {
  let res = (^bash -lc $cmd | complete)
  if $res.exit_code != 0 {
    error make {
      msg: $"command failed: ($cmd)"
      label: {
        text: $"stdout:\n($res.stdout)\n\nstderr:\n($res.stderr)"
        span: (metadata $cmd).span
      }
    }
  }
  $res.stdout | str trim --right
}

def render-file [output_file: string, title: string, specs: list<record<name: string, cmd: string>>] {
  mkdir ($output_file | path dirname)

  let header = [
    "<!-- AUTO-GENERATED by docs/scripts/generate-cli-reference.nu -->"
    ""
    "_Do not edit by hand. Regenerate with:_"
    ""
    "```bash"
    "nu docs/scripts/generate-cli-reference.nu"
    "```"
    ""
    $"# ($title)"
    ""
  ] | str join (char nl)

  let blocks = ($specs | each {|spec|
    let output = (run-cmd $spec.cmd)
    [
      $"## `($spec.name)`"
      ""
      "Command:"
      ""
      "```bash"
      $spec.cmd
      "```"
      ""
      "Output:"
      ""
      "```text"
      $output
      "```"
      ""
    ] | str join (char nl)
  } | str join (char nl))

  ($header + $blocks) | save --force $output_file
  print $"Generated: ($output_file)"
}

let ab_specs = [
  { name: "ab", cmd: "cargo run -q -p ab -- --help" }
  { name: "ab new", cmd: "cargo run -q -p ab -- new --help" }
  { name: "ab spawn", cmd: "cargo run -q -p ab -- spawn --help" }
  { name: "ab info", cmd: "cargo run -q -p ab -- info --help" }
]

let portal_specs = [
  { name: "agent-portal-host", cmd: "cargo run -q -p agent-portal --bin agent-portal-host -- --help" }
  { name: "agent-portal-cli", cmd: "cargo run -q -p agent-portal --bin agent-portal-cli -- --help" }
  { name: "wl-paste wrapper", cmd: "cargo run -q -p agent-wrappers --bin wl-paste -- --help" }
]

render-file "docs/src/reference/agent-box/cli.md" "Agent-box CLI reference" $ab_specs
render-file "docs/src/reference/portal/cli.md" "Portal CLI reference" $portal_specs

print "Done."
